version: "3.7"
services: 
    web_prod:
        container_name: web_prod
        build:
            context: .
            dockerfile: './docker/web_prod.Dockerfile'
        depends_on:
            - server
        ports: 
            - "3003:80"
        environment:
            - REACT_APP_SERVER
            - REACT_APP_SERVER_PORT
        volumes:
            - web_modules:/web/node_modules
    server:
        build:
            context: .
            dockerfile: './docker/server.Dockerfile'
        depends_on:
            - mongodatabase
        ports: 
            - "9002:9002"
        restart: on-failure
        environment:
            - DB_URL=mongodb://mongodatabase:27017/pantry
            - SERVER_HOST_URL
            - SERVER_HOST_PORT
            - AUTH_SECRET
        volumes:
            - server_modules:/src/node_modules
    mongodatabase: 
        image: mongo
        ports: 
            - "27020:27017"
        volumes: 
            - mongodb_data_container:/data/db
volumes:
    web_modules:
    server_modules:
    mongodb_data_container:
